### ISSUE TITLE
חשוב - נראה שאלגוריתם סידור הכתובות מציע מסלול ארוך ולא עפ"י סדר הנסיעה

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#21]
ראו תצלום מסך - הייתי מצפה שאחרי נק' #1 המערכת תפנה לנק' #5 שהיא הקרובה ביותר. גם בהמשך הייתי מצפה שיופנו לנק' #4 כו'. כך מושג מסלול קצר יותר (לא צריך לחזור חזרה לנק' #5) ומחלקים את המשלוחים לאורך הנסיעה מצפון לדרום. הפתרון כנראה צריך להיות מציאת הנקודה הרחוקה ביותר מנקודת ההתחלה וקבלת מסלול המסירה עד אליה
![image](https://user-images.githubusercontent.com/30443321/54879954-1943db00-4e48-11e9-8548-5d5da3112d8c.png)

**Comment by noam-honig** [comment]
לשקול לשנות את המסלול להסתיים בנקודה הרחוקה ביותר.
