### ISSUE TITLE
מסך 'כתובות בעייתיות' לא מציג הערות מסירה של משנע מהאירוע הקודם לגבי כתובת בעייתית

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#22]
במצב הנוכחי לא ברור איך רואים את הערות המסירה מהאירוע (או אירועים) הקודם. יתכן ויש שם הערה שתסייע לעדכון הכתובת
![image](https://user-images.githubusercontent.com/30443321/54879978-72137380-4e48-11e9-97be-71d390c3c4db.png)

**Comment by noam-honig** [comment]
אפשר להוסיף עוד עמודה - אבל היא תגרום לכפתורים להדחף לשמאל ותהפוך את החיפוש בגוגל לפחות נח - מה אתה אומר?

**Comment by hi-shai** [comment]
עיקר העבודה עם המסך תהייה במצב דסקטופ לכן יש פחות בעיה של רוחב מסך. כשליש מסך היה ריק כשקיפלתי את התפריט בצד 
האם אפשר לשלוט ברוחב העמודות? אם כן אפשר לצמצם מעט את רוחב השם והערת הכתובת. גם הערות מסירה ברוב מקרים יהיה ריק אך כאשר יופיע בו תוכן זה מידע חשוב

**Comment by noam-honig** [comment]
המשתמש יכול להוסיף את מה שהוא /היא רוצה - וכרגע נראה שהם עושים את זה בשמחה
