### ISSUE TITLE
לעתיד - אין גישה אירועים שהסתיימו

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#23]
כרגע, מרגע שהסתיים אירוע כל המידע שלו הופך ללא נגיש. למלבד העתקת המשפחות סביר להניח שמנהל/ת המערכת ירצו לראות מידע נוסף: למשל כמה סלים, משפחות ומתנדבים היו באירועי ראש השנה ופסח בשנתיים-שלוש האחרונות, איזה משפחות לא קיבלו סלים, מה היו ההערות של המתנדבים ועוד.
עבור משפחה - הייתי רוצה לראות סיכום כללי (בכמה אירועים שויכו, כמה נמסר בהצלחה וכמה לא נמסר) ובכל אירוע שקרה, מה הם קיבלו, מי שינע אליהם, מה היו ההערות שלו.
עבור משנע - סיכום כללי (בכמה אירועים השתתף, כמה מסר בהצלחה וכמה לא מסר) ובכל אירוע שקרה, לכמה משפחות מסר, לאיזה משפחות, מה הם קיבלו, סטטוס המסירה ומה היו ההערות שלו.
עבור כל אירוע בעבר: כמה משפחות היו, כמה סלים ומאיזה סוג, כמה מסירות מיוחדות היו, כמה משנעים השתתפו, כמה נמסרו בהצלחה וכמה בעיות היו, איזה הערות היו למשנעים,

**Comment by noam-honig** [comment]
נוסף מסך היסטורית משלוחים דרכו אפשר לעשות סינונים ולראות את כל המידע - כמו כן אפשר ליצא לאקסל ולעשות שם דוחות.
