### ISSUE TITLE
לעתיד - (שיוך משפחות) טקסט ההנחיות בקליטת משנע כתוב היטב אך בולט מידי

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#24]
אחרי כ- 3-4 קליטות משנעים ושיוכם למשפחות חשיבותו תפחת
הצעה: להציג טקסט באופן פחות בולט ע"י הצגתו באפור ו/או הקטנת הגופן
![image](https://user-images.githubusercontent.com/30443321/54880212-0e3e7a00-4e4b-11e9-8d45-eeabc41fc582.png)

**Comment by noam-honig** [comment]
נדון ונדחה

**Comment by hi-shai** [comment]
מדובר בתיקון יחסית מינורי: האפרת טקסט ו/או הקטנת גופן
לאור השימוש המסיבי במסך הזה, שהוא צוואר בקבוק במערכת, שווה לשקול מחדש

**Comment by hi-shai** [comment]
![image](https://user-images.githubusercontent.com/30443321/57302949-fa8e6080-70e4-11e9-9844-e59136ca0273.png)
