### ISSUE TITLE
 צ'ק בוקס ללא תאור

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#241]
בשיוך משפחות, שיוך משפחות למשנע, לחיצה על 3 נקודות משמאל נפתחים צ'ק בוקס ללא תאור

**Comment by menachemai** [comment]
![image](https://user-images.githubusercontent.com/20454933/74140429-b8f38e80-4bfd-11ea-9dcd-abd04c13125c.png)

**Comment by noam-honig** [comment]
תוקן

**Comment by noam-honig** [comment]
תוקן
*Noam Honig  *
*Founder & **CEO*
*www.fireflymigration.com <http://www.fireflymigration.com/>*
[image: Inline image 1]
[image: Inline image 5] <http://www.youtube.com/fireflymigration>[image:
Inline image 4]
<http://www.linkedin.com/company/firefly-migration/100-automated-migration-from-magic-unipaas-xpa-to-net-23400981/product>
