### ISSUE TITLE
לעתיד נקודה למחשבה - (שיוך משפחות) סינוני פרטי השינוע (שפות וערים) אינם בשימוש תכוף אך תופסים מקום

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#25]
הצעה: להסתיר סינונים אלו תחת קישור אקורדיון, כמו שפרטי משפחות לחלוקה מוצגים

![image](https://user-images.githubusercontent.com/30443321/54880246-7725f200-4e4b-11e9-9235-ae79a7f3d749.png)

**Comment by noam-honig** [comment]
מה אתה מציע?

שפות נראה לי לא שימושי - אבל ערים נראה לי שכן.

צריך לאסוף על זה מידע

**Comment by hi-shai** [comment]
אני מציע להסתיר שדות פחות שימושיים תחת קישור בשם 'אפשרויות נוספות' או ניסוח דומה

**Comment by noam-honig** [comment]
כרגע הבעיה שלי עם זה שכפתור יקח בדיוק את אותו המקום מבחינת גובה כמו של האפשרויות שיש כרגע - כך שזה לא יחסוך מקום.

אם בהמשך יהיו עוד אפשרויות סינון אז זה יהיה הגיוני יותר.

**Comment by hi-shai** [comment]
קישור אמור להיות קטן יותר מכפתור ולהיות מוצג עם רקע שקוף, כך שיתפוס פחות תשומת לב

**Comment by noam-honig** [comment]
בטלפון נייד - עם אצבעות עבות קישור קטן זה פחות עדיף

*Noam Honig  *
*Founder & **CEO*
*www.fireflymigration.com <http://www.fireflymigration.com/>*
[image: Inline image 1]
[image: Inline image 5] <http://www.youtube.com/fireflymigration>[image:
Inline image 4]
<http://www.linkedin.com/company/firefly-migration/100-automated-migration-from-magic-unipaas-xpa-to-net-23400981/product>

**Comment by hi-shai** [comment]
מאחר וזו פעולה פחות שכיחה הנגישות שלה פחות חשובה. הנה דוגמא מדוקטור גוגל
![image](https://user-images.githubusercontent.com/30443321/57194434-a00fcb80-6f4f-11e9-9216-9e387b2c717d.png)

**Comment by noam-honig** [comment]
בדוגמא שנתת הלינק אין שום דבר מעל או מתחת ללינק
*Noam Honig  *
*Founder & **CEO*
*www.fireflymigration.com <http://www.fireflymigration.com/>*
[image: Inline image 1]
[image: Inline image 5] <http://www.youtube.com/fireflymigration>[image:
Inline image 4]
<http://www.linkedin.com/company/firefly-migration/100-automated-migration-from-magic-unipaas-xpa-to-net-23400981/product>

**Comment by hi-shai** [comment]
![image](https://user-images.githubusercontent.com/30443321/57221336-85992900-7007-11e9-9402-04180f06b095.png)
דוגמא ב: מעל יש טקסט, מתחת תמונה וטקסט דומיננטיים. רואים שהקישור של
More...
מינורי יחסית: לא תופס הרבה קשב ויזואלי אך כן מאפשר לפעול

דוגמא ג: רואים את ההבדל בין הכפתורים לבין הצגת הסינונים הנוספים
![image](https://user-images.githubusercontent.com/30443321/57221844-44097d80-7009-11e9-9c1e-733250882324.png)
![image](https://user-images.githubusercontent.com/30443321/57221879-64393c80-7009-11e9-8c40-8ce536d6a46e.png)

נראה לי שהנקודה יחסית ברורה. אם לא - תגיד

**Comment by noam-honig** [comment]
עדיין חולק איתך כי שתי הדוגמאות לא דומות - ליד הMORE אין כלום ללחוץ.

והחץ של STAR RATING פותח שטח ענק שבהחלט שווה לחסוך אותו.

במקרה שלנו השטח שיחסך מבחינת גובה הוא באותו הגובה שנצטרך להקצות ללינק.
*Noam Honig  *
*Founder & **CEO*
*www.fireflymigration.com <http://www.fireflymigration.com/>*
[image: Inline image 1]
[image: Inline image 5] <http://www.youtube.com/fireflymigration>[image:
Inline image 4]
<http://www.linkedin.com/company/firefly-migration/100-automated-migration-from-magic-unipaas-xpa-to-net-23400981/product>
