### ISSUE TITLE
לעתיד - [נקודה למחשבה] האם לתת למתנדבת השיוך אפשרות לנסות לבצע תיקון מהיר של כתובת

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#27]
בדוגמה הכתובת הנכונה היא 'אברהם אבו שדיד 20 נתניה' (ולא 'אבו שדיד 20 נתניה'). אולי כדאי לתת למתנדבת השיוך לקחת את הכתובת כפי שגוגל הבין וכך לתקן במהירות את הכתובת ולשמור אותו?

![image](https://user-images.githubusercontent.com/30443321/54880347-67f37400-4e4c-11e9-9c66-5f5d8413bff4.png)

**Comment by noam-honig** [comment]
כפול של #13
