### ISSUE TITLE
לעתיד - (שיוך משפחות) מופיעים חיתוכים עפ"י שפות למרות שאין משפחות לחלוקה שדוברות שפה זו

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#28]
הצעה: ליד שם שפה לציין בסוגריים את מספר המשפחות דוברות השפה. אם אין, לכתוב אפס ולהאפיר את שם השפה
![image](https://user-images.githubusercontent.com/30443321/54880390-c4569380-4e4c-11e9-9d5c-0ae1c104eb02.png)

![image](https://user-images.githubusercontent.com/30443321/54880397-cddffb80-4e4c-11e9-95f8-38807cd4d7b2.png)

**Comment by noam-honig** [comment]
לא משוכנע- כל נושא השפות נראה לי כמו משהו שהיה הגיוני באפיון אבל בפועל לא השתמשו בו - אני שוקל להוריד אותו כלל.

**Comment by hi-shai** [comment]
יש כאן שני נושאים שמתערבבים זה בזה
א. אם כלל לא עושים שימוש בשדה השפה אז צריך להוריד אותו. צריך בשביל זה לקבל מידע מהשטח. צריך לזכור שבמעט משפחות שכן זקוקות לדובר השפה - רוסית, אמהרית או ערבית ביפו - זה עשוי להיות משמעותי עבורם
ב. הבאג הוא על כך שמוצגות שפות למרות שאין אף משפחה לחלוקה שמקוטלגת כדוברת השפה. ז"א הצגת השפה שאין לה משפחות מעמיסה את הממשק ומסבכת את עבודת מתנדבות שיוך משפחות שלא לצורך

לכן הפתרון המוצע הוא ליד שם שפה לציין בסוגריים את מספר המשפחות דוברות השפה. אם אין, לכתוב אפס ולהאפיר את שם השפה

**Comment by noam-honig** [comment]
בהתבסס על הנתונים של פסח 2019 - לא נעשה שימוש כלל בשדה שפה.

השימוש היחידי היה של עמותה ששינתה את היעוד של השדה משפה ל"יכולים לרדת לקחת מהרכב" מה שהיה חשוב למשנעים מסויימים.

**Comment by hi-shai** [comment]
יש פה מספר בעיות
א. בעיה כללית - הצגת שדה ברשימת דופדאון למרות שאין רשומות שעונות לקריטריון הזה
במקרה הזה מוצגת השפה האמהרית למרות שאין אף משפחה דוברת אמהרית לשיוך
![image](https://user-images.githubusercontent.com/30443321/57194020-3e009780-6f4a-11e9-93b9-73d42877674b.png)
את הפתרון ציינתי בתיאור בעיה המקורית

ב. בעיה ספציפית - האם יש צורך בחיתוך עפ"י שפה בשיוך משפחות
(כאמור זה קשור בעקיפין לבאג שתואר)
השימוש בחיתוך עפ"י עיר מגורים בוודאות יותר שכיח, בייחוד בעמותות גדולות שמחלקות במספר ערים, לכן צריך להעביר אותו ימינה, שיהיה השדה הראשון
אם לא היה שימוש בשדה הזה, לא פחות חשוב, **אנחנו לא צופים שום שימוש בעתיד בשדה השפה**, אפשר להוריד אותו
אם יש סיכוי שבל זאת יזדקקו לו, למשל בעמותות גדולות או בעמותות שעוזרות לעולים ממדינה מסוימת, אפשר להסתיר את החיתוך עפ"י שפה תחת קישור 'הצגת אפשרויות נוספות'. כך זה לא יתפוס מקום אך יהיה זמין בעת הצורך
