### ISSUE TITLE
לעתיד - הודעת אס.אם.אס ושאר ההודעות למשנעים הן בלשון זכר

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#29]
בחלק מהמקרים אלו יהיו משנעות

הצעות:
הגדרת המגדר של המשנע/ת בקליטתו והצגת הודעות עפ"י המגדר
- או -
שימוש בלשון רבים (למשל 'לחצו'), שבו ההבדל המגדרי פחות מורגש

**Comment by noam-honig** [comment]
אני לא רוצה לקלוט מגדר.

אנא שלח את התיקון של ההודעות מלשון זכר ללשון רבים.
פרט ניסוח הודעה נוכחי - ואיך לדעתך צריך לכתוב את זה בזכר.
פתח לזה ISSUE נפרד כאשר תגיע לזה כדי שנתקדם.
