### ISSUE TITLE
חשוב - (משפחות | באירוע) שם האירוע לא מופיע, לכן פחות ברור מה מנהלים

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#30]
כרגע יש אירוע פעיל אחד. במצב בו יש שני אירועים בסמיכות אחד לשני, למשל פורים ופסח, זה עלול לבלבל. בהמשך בהחלט יכול להיות מצב שבו שני אירועים יתנהלו במקביל

הצעה: להוסיף את שם האירוע לראש הדף (למשל: 'משפחות (ראש השנה 2018)') או מתחת לכותרת הדף ומעל הטאבים

![image](https://user-images.githubusercontent.com/30443321/54880498-c9681280-4e4d-11e9-8421-00937d69e5d7.png)

**Comment by noam-honig** [comment]
נושא האירועים יורד מהמערכת - במקום זה יש משלוחים למשפחה - ויש מסך "היסטורית משלוחים" שבוא אפשר לראות את כל המשלוחים ולסנן לפי תאריכים וכו...
