### ISSUE TITLE
לעתיד - (משפחות | באירוע), (בעיה כללית) לא ברור איך חוזרים ממצב טבלאי לצפייה עפ"י רשומה בודדת

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#32]
נייד לא נוח לצפות במידע מצב טבלאי. לכן כשעוברים למצב טבלאי (כנראה בטעות), יש צורך לחזור לצפייה עפ"י רשומה בודדת. לא ברור איך עושים זאת. הדרך היחידה שמצאתי הייתה ללכת למסך אחר (למשל שיוך משפחות) ואז לחזור למסך משפחות
![image](https://user-images.githubusercontent.com/30443321/54880571-9d00c600-4e4e-11e9-8f14-9d3eb132638f.png)
![image](https://user-images.githubusercontent.com/30443321/54880575-a68a2e00-4e4e-11e9-9431-e91e55bb454e.png)
הצעה: להוסיף כפתור של 'מצב רשומה בודדת'. מיקומו יהיה שני משמאל (היכן שהיה כפתור מעבר למצב טבלאי, כך שהוא יהיה Toggle שלו)

**Comment by noam-honig** [comment]
כפתור העפרון שרואים בתמונה מעביר את המערכת למצב רשומה בודדת
![image](https://user-images.githubusercontent.com/16635859/54882896-8c107e80-4e67-11e9-94bb-82607f11b04c.png)

בכל מקרה הגירד הוחלף לגירד אחר כך שהריד שמתואר כאן לא רלוונטי

**Comment by hi-shai** [comment]
הגריד הוחלף אך התיאור המילולי של הבעייה עדיין רלוונטי. הבעיה היא שהמעבר למצב טבלאי מתבצעת מאזור הפקדים
![image](https://user-images.githubusercontent.com/30443321/54885625-e79e3480-4e86-11e9-86fb-f589ec183991.png)
אך כאשר עוברים למצב טבלאי אין שם כפתור שיחזיר למצב רשומה בודדת
כפתור המעבר מחייב גלילה אופקית, ומופיע כמה פעמים, מה שהופך את התפעול למורכב יותר
![image](https://user-images.githubusercontent.com/30443321/54885677-a195a080-4e87-11e9-9a53-3af308a54a63.png)
