### ISSUE TITLE
לעתיד - מסך 'כתובות בעייתיות' לא מציג מהו היקף הכתובות הבעייתיות ביחס לכמות הכללית של המשפחות באירוע

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#33]

**Comment by noam-honig** [comment]
למה צריך את זה?

**Comment by hi-shai** [comment]
כי מצב שבו יש 5 משפחות בעייתיות מתוך 200 משפחות שונה ממצב שבו יש 50 משפחות בעייתיות מתוך 200 משפחות

באופן כללי: הצגת היקף הבעיה עוזרת להבין את חומרתה מניעה לפתרון

![image](https://user-images.githubusercontent.com/30443321/57194253-781f6880-6f4d-11e9-8dc0-3a521be85c2d.png)
באתר הבדיקות יש המון משפחות עם כתובת בעייתית, כך שהתמונה לא ממש משקפת את המציאות
