### ISSUE TITLE
לעתיד - (משפחות | באירוע), בתצוגת משפחה בודדת התכנים לא מיושרים לכן פחות נוח לסקור את המידע

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#34]
הצעה: לישר את התכנים עפ"י התוכן השמאלי ביותר, ז"א פרטי משפחה, בתמונה 'אלפר'
![image](https://user-images.githubusercontent.com/30443321/54880609-11d40000-4e4f-11e9-8682-d1733e8060ed.png)

**Comment by noam-honig** [comment]
זה בכוונה - כדי לנצל יותר טוב את הרוכב

**Comment by hi-shai** [comment]
פחות נוח לסקור מידע שאינו מיושר. עיקר העבודה היא במצב דסקטוב, שבו אין בעיית רוחב

**Comment by hi-shai** [comment]
![image](https://user-images.githubusercontent.com/30443321/57300693-04fa2b80-70e0-11e9-9aaa-38731b6982bb.png)
