### ISSUE TITLE
לעתיד - (משפחות | כללי) כפתורים של פעולות שכיחות (דפדוף קדימה ואחורה) מוצגים כיחידה אחת עם אפשרויות מתקדמות (בחירת שדות תצוגה) והוספת רשומה

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#35]
הצעה: להפריד בין כפתורים של פעולות שכיחות (דפדוף קדימה ואחורה) ואולי סינון לבין אפשרויות מתקדמות (בחירת שדות תצוגה) והוספת רשומה, למשל בקו חוצץ
![image](https://user-images.githubusercontent.com/30443321/54880744-0eda0f00-4e51-11e9-81e2-f13ac10316d4.png)

**Comment by noam-honig** [comment]
הגריד כולו הוחלף הISSUE מדבר על הגריד הישן

**Comment by hi-shai** [comment]
אכן הופיע תצלום מסך של הגריד הישן אך תיאור הבעיה המילולי עדיין רלוונטי.
הפעולות השכיחות הן דפדוף והן אינן ממוקמות מימין, ששם פעולות שכיחות צריכות להיות. כרגע מימין ממוקמות אפשרויות מתקדמות - בחירת שדות תצוגה

![image](https://user-images.githubusercontent.com/30443321/54885454-dce2a000-4e84-11e9-981b-93758f3d728a.png)
