### ISSUE TITLE
לעתיד - שיפור אלגוריתם השיוך למתנדב שהחל וסיים לחלק כך שיקבל משפחות בסביבה

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#46]
כאשר מתנדב סיים לחלק - סימן שחילק בהצלחה או שהייתה בעיה במשפחה - ורוצה לחלק עוד הוא יקבל משפחות שאינן בהכרח באזור בו חילק. זה בעייתי בכמה תרחישים

א. הייתה בעיה עם אחת המשפחות. כעת מתנדב השינוע נמצא עם ארגז / סל מיותר. שסביר להניח שבשכונה או בסביבה יש בה עוד משפחות שממתינות לסלי מזון. כיום ברגע שכל המשפחות חולקו - בהצלחה או הייתה בעיה בכתובת או במשפחה - האלג' יקצה למתנדב משפחה אקראית שיתכן שתהייה רחוקה מהמקום בו הוא נמצא

ב. מתנדב סיים לחלק בהצלחה וחוזר למרכז החלוקה לחלק סלים נוספים. במקרים רבים יהיה למתנדב השינוע קל יותר לשכונה בה כבר חילק, הן בסבב הנוכחי והן באירועי חלוקה מהעבר. המתנדב כבר נסע לאזור והתמודד עם בעיות ניווט וחניה באזור

**Comment by noam-honig** [comment]
המטרה היא שכאשר מתנדב נתקל בבעיה ונשאר עם סלים - אז כשמוסיפים לו סל, שזה יהיה ליד הסל האחרון שהוא חילק ולא סתם במיקום כלשהו
