### ISSUE TITLE
מעבר בקליק ממסך מעקב משנעים למסך שיוך משפחות של מתנדב השינוע בו צופים

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#47]
נניח התקשרו למתנדב שהתעכב וגילו שהוא לא הצליח לחלק לאחת המשפחות בגלל בעיה בכתובת. במקרה שכזה רוצים להקצות לו עוד משפחה כי יש לו ארגז מיותר ברכב

במקרה שכזה כיום צריך ללכת למסך מעקב משנעים, לרשום את מספר הטלפון של המתנדב ומשם ללכת למסך שיוך משפחות ורק אז להוסיף משפחה למתנדב השינוע

**Comment by hi-shai** [comment]
![image](https://user-images.githubusercontent.com/30443321/56392634-9ccfcc80-623a-11e9-8766-d542e97cb62a.png)

**Comment by noam-honig** [comment]
בהתייחס ל "במקרה שכזה כיום צריך ללכת למסך מעקב משנעים, לרשום את מספר הטלפון של המתנדב ומשם ללכת למסך שיוך משפחות ורק אז להוסיף משפחה למתנדב השינוע"
במסך שיוך משפחות יש חיפוש לפי שם של המשנע (לחיצה על הזכוכית מגדלת בצד ימין למעלה)

**Comment by hi-shai** [comment]
הבהרה: מספר הטלפון של המשנע מופיע כקישור
'התקשרי לנועם 0507330590'
לא ניתן לבצע העתק ואח"כ הדבק של המספר. חייבים לזכור את המספר בע"פ או לרשום אותו על נייר, כדי להשתמש בו בהמשך

לכן נדרש קישור למתנדב השינוע, רצוי שיופיע מתחת לכפתורי הפעולה
(בנוסף לכך הצורך לנווט למתנדב שינוע קשור לבאג אחר #46 )

**Comment by noam-honig** [comment]
האופצייה הקיימת היום עבור המשתמש היא ללכת למסך שיוך משפחות ולחפש את המשנע
לפי שם (בעזרת לחיצה על הזכוכית מגדלת).
הנושא הוסבר למשתמשת


*Noam Honig  *
*Founder & **CEO*
*www.fireflymigration.com <http://www.fireflymigration.com/>*
[image: Inline image 1]
[image: Inline image 5] <http://www.youtube.com/fireflymigration>[image:
Inline image 4]
<http://www.linkedin.com/company/firefly-migration/100-automated-migration-from-magic-unipaas-xpa-to-net-23400981/product>

**Comment by hi-shai** [comment]
נכון אך גם זה דורש הקלקות נוספות

במסך שיך המשפחות, המיקום של זכוכית המגדלת בשדה של מספר הטלפון מבלבל. במיקום הנוכחי - בתוך שדה המספר - קשה לצפות לכך שהיא תאפשר חיפוש עפ"י שם 
(זו בעיה אחרת שאינה קשורה לבעיה המקורית)
