### ISSUE TITLE
לעתיד - תמיכה ביותר מאירוע חלוקה בודד פעיל

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#49]
במרכז מזון ביפו חלק מהקשישים מקבלים סלי מזון פעמיים בחודש, בתחילת החודש ובסופו. החלוקה עבורם צריכה להתבצע *במקביל* לשאר המשפחות שמקבלים סל אחד בחודש

למעשה צריכים תמיכה בשלושה אירועים במקביל
רגילים - למשך כל החודש
קשישים כפול תחילת החודש
קשישים כפול סוף החודש

**Comment by hi-shai** [comment]
חשוב לציין, שלא רוצים שיקרה מצב בו קשישים שמקבלים שני סלים יקבלו אותם בסמיכות, למשל יום אחר יום, אלא בחתחילה בחצי הראשון של החודש ואחר כך בחלק השני של החודש

**Comment by noam-honig** [comment]
בפרטי משפחה מופיע היסטרית המשלוחים שלה ואפשר לראות שם הכל
