### ISSUE TITLE
לעתיד - הצגת היסטוריה של משפחה שטוענת שלא קיבלה סל

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#50]
חלק מהמשפחות שהסל הושאר ליד ביתן, טענו שלא קיבלו את הסל

במקרה שכזה צריך להעביר את המשפחה שוב למצב מוכן לשיוך כדי שיקבלו סל חדש

רצוי להציג את היסטוריית החלוקה למשפחות אלו: לפעמים בן משפחה אחד לא יודע שאחר קיבל את הסל ולפעמים רצוי להוסיף הוראות למשנע. בכל מקרה מרכז החלוקה מעוניין לדעת על היסטוריית בעיות עם החלוקה למשפחה

בנוסף לכך צריך לעדכן את סך כל הסלים שחולקו באירוע, כי המשפחה קיבלה למעשה שני סלים

**Comment by noam-honig** [comment]
יש בפרטי משלחה לשונית של היסטוריה
