### ISSUE TITLE
להוסיף כפתורים ב"משלוחים שלי" של מתנדב שיהיו בולטים יותר בטלפון של המתנדב (בדומה לשני הלינקים שמוגדרים בהגדרות מערכת)

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#518]
למעשה הפתרון צריך להיות שבמקרה של "מתחשבים" (settings.isSystemForMLT), הלינקים שמוגדרים בהגדרות מערכת יופיעו ככפתורים ולא כטקסט. שינוי קל ב HTML שצריך לפעול רק במקרה של "מתחשבים".

**Comment by noam-honig** [comment]
אני לא מכיר אפשרות כזו בהודעת SMS - אם קיבלת SMS כזה פעם תשלחו לי ואחקור אותו.

בכל מקרה אתם יכולים לשנות את הודעת הSMS להיות מה שתרצו - במסך הגדרות מערכת.
![image](https://user-images.githubusercontent.com/16635859/88630261-00d97580-d0b9-11ea-8bb2-059efa89728d.png)

**Comment by morfi11** [comment]
הכוונה לא בהודעת סמס אלא במסך שנתפח כשהמתנדב פותח את הסמס. 
יש שני לינקים עם טקסט חופשי שמופיעים בראש העמוד.
מסתבר שהמתנדבים לא רואים את הלינקים ומפספסים מידע

**Comment by noam-honig** [comment]
אני רוצה להשאיר את הלינקים כפי שהם בינתיים.

תוסיף דברים ספציפים לכם איך שבא לך בנוסף

**Comment by morfi11** [comment]
ראה גם https://github.com/noam-honig/food-basket-delivery/issues/539
