### ISSUE TITLE
מסך כתובות בעייתיות- חסר כפתור לבדוק כתובת

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#52]
במסך כתובות בעייתיות, אם עודכנה הכתובת, למשל אחרי שיחה טלפונית עם המשפחה, יש צורך לוודא שהכתובת המתוקנת אכן תקינה

הדרך הנוכחית היא לרענן את כל הכתובות הבעייתיות ולראות שיש פחות משפחה בעייתית 

זה פחות נוח כי בדרך כלל מתקנים את המשפחות ברשימה, זו אחר זו, כך שנצטרך לנווט חזרה למקום אליו הגענו. בנוסף לכך פחות נוח לראות שהתיקון הצליח

**Comment by noam-honig** [comment]
הבדיקה של תקינות הכתובת העשית בעת השמירה - כלומר איך שהמשתמש לוחץ על הV של השמירה מתבצעת בדיקה של תקינות הכתובת - ואם הכתובת תקינה מוסר ממנה הסימן הצהוב של כתובת לא תקינה
