### ISSUE TITLE
add thank-you email in registger-donor and register-helper

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#526]
once register is submitted, create an email with predefined text and send to the user email as registered in the form. 
The email text should be defined by the admin of the system - next to the SMS texts that are defined. It should be a template that allows adding the donor/helper name, phone number, email address, etc.

**Comment by noam-honig** [comment]
1. Please setup an email account that'll be used to send these emails and follow up on them.
2. I recommend that v1 will be a fixed text that you'll start with and v2 will be the custom editing for the users.
Good luck doing it 👍

**Comment by morfi11** [comment]
we have an email account in gmail. 
this issue is assigned to Yakov Abrams - need to add him here and assign the issue to him: 
Yakov.abrams@gmail.com

**Comment by morfi11** [comment]
Sender email account is hello@mitchashvim.org.il

I have the password
