### ISSUE TITLE
לאפשר מחיקה של משלוח "בעייה" בלי לעבור דרך "הקפאה" (או להקפיא ולמחוק בלחיצה אחת)

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#528]

**Comment by noam-honig** [comment]
למה לאפשר מחיקה של משלוח בעיה?
בחלוקות רגילות אני לא רוצה לאבד את המידע הזה - צריך להעביר משלוח זה לארכיב

**Comment by morfi11** [comment]
will add new problem status for "decline" (code 24)
