### ISSUE TITLE
מסך "רשימת מעבדות" ממויינת לפי מרחק שתוצג למתנדב בלחיצת כפתור

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#544]
כיום כאשר מתנדב נכנס ללינק סמס הוא רואה את רשימת המשלוחים ובסופה נמצאת כתובת המעבדה.
נדרש לאפשר למתנדב להחליט ולשלוח למעבדה אחרת.
כאשר מרחיבים את השורה של המשלוח האחרון (המעבדה) - יהיה כפתור "הצג רשימת מעבדות חליפיות"
במסך החדש יוצגו כם המעבדות עם השדות:
שם המעבדה, שם איש קשר, טלפון איש קשר, עיר (לפי הכתובת הרשומה), מרחק ממיקום נוכחי
המתנדב יוכל ללחוץ על מעבדה ובכך להחליף את היעד של כל המשלוחים ואת השורה האחרונה ברשימה

**Comment by morfi11** [comment]
@bwknight - Yakov - please note the other tasks are no longer needed (already resolved). 
This one is what we need now.

**Comment by bwknight** [comment]
@morfi11 noted. starting work on this
