### ISSUE TITLE
כללי - מעבר בין רשימות מעביר לתחילת הרשימה שאינו רלוונטי

### ISSUE THREAD

**Issue by hi-shai** [noam-honig/food-basket-delivery#55]
בסקירה ודפדוף של משפחות בסטאטוס בדרך ומעבר לרשימת בעיות, אם חוזרים לרשימת בדרך חוזרים לתחילת הרשימה שאינו רלוונטי כי קודם כבר דיפדפנו ברשימה

**Comment by noam-honig** [comment]
לא הבנתי - אנא צרף תמונות

**Comment by hi-shai** [comment]
א. בסקירה ודפדוף של משפחות בסטאטוס בדרך, הגעה למשפחה השלישית
![image](https://user-images.githubusercontent.com/30443321/57194762-44dfd800-6f53-11e9-9ab1-bc1140451bb3.png)

ב. מעבר לרשימת בעיות
![image](https://user-images.githubusercontent.com/30443321/57194763-5628e480-6f53-11e9-8fd6-268504981e6b.png)

ג. חזרה לרשימת 'בדרך', מביאה אותנו לתחילת הרשימה למרות שקודם היינו במשפחה השלישית ברשימה
![image](https://user-images.githubusercontent.com/30443321/57194778-8a9ca080-6f53-11e9-97b4-d6f4850d9d55.png)

השאיפה היא לחזור למקום בו היינו, אם המשפחה הזו עדיין מופיעה ברשימה
