### ISSUE TITLE
להוסיף סטטוס של הוסרו מהרשימה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/food-basket-delivery#59]
כמו לא באירוע - רק פחות זמני :)
רלוונטי למשפחות שלא רוצות לקבל - או נפתרו וכו...

להציג את זה בפיא של כל המשפחות

**Comment by hi-shai** [comment]
הכוונה היא למשפחות שנפטרו :-)

**Comment by noam-honig** [comment]
בוצע
