### ISSUE TITLE
מעקב משנעים

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#6]
בבחירת משנע מנחם המערכת לא מגיבה/נתקעת
לאחר כדקה מקבלים הודעת P
![2019-01-08_14h18_21](https://user-images.githubusercontent.com/20454933/50835535-9be7ee80-135f-11e9-963f-61e2d200ad43.jpg)
![2019-01-08_14h18_21](https://user-images.githubusercontent.com/20454933/50835566-b0c48200-135f-11e9-9a70-a8c596446137.jpg)

**Comment by noam-honig** [comment]
Fixed
