### ISSUE TITLE
במסך האר המשאלות - ניתן להעניק מתנה למתנדב ע"י בחירת המתנדב בעמודה המתאימה

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#649]
המסך לבחירת מתנדב אינו מראה מתנדבים מוקפאים 

יש לאפשר הצגה של מתנדב מוקפא ברשימה רק אם הרשימה עבור חיפוש מסוג זה
בדר"כ החיפוש נועד לשיוך ואז לא אמורים לראות מתנדבים קפואים

**Comment by lionsh29** [comment]
I'm on it
