### ISSUE TITLE
show helpers from specific org

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#665]
בהיסטורית משלוחים, לאפשר סינון לפי:
"אתר רישום" 
ו\או "ארגון" 
כדי להציג רק מתנדבים המשוייכים לארגון מסויים. כמו כן לוודא שייצוא לאקסל מתייחס לסינון
הסינון צריך להיות איחוד של שני התנאים
(helper.company like form.companyFilter) OR (urlDbOperator(h.referredBy.defs.dbName) like form.URLFilter)

**Comment by noam-honig** [comment]
זה פחות פשוט ממה שזה נשמע.

ההמלצה שלי לעשות את זה בעזרת entity שיורש מfamilydeliveries, ומוסיף חו עוד
עמודות מבוססות נוסחת sql
