### ISSUE TITLE
בכל מסכי הניהול - יש להתייחס לתורם עם כל התרומות שלו ולא לפי תרומה

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#668]
למשל במסך משלוחים פעילים, ממיין לפי כמות במשלוח ויכול לפםספס תורם שיש לו סה"כ כמות גדולה אבל משלוח אחד גדול ואחר קטן

**Comment by noam-honig** [comment]
בתחילת הדרך - היתה שורה אחת במשלוחים פעילים פר תרומה - והפירוק
למחשב/מסך/נייד היה בהערות או משהו כזה.

אח"כ עברנו למודל שיש שורה פר סוג פריט (מחשב, מסך, נייד וכו...)

אם אני קורא נכון את המפה - נראה לי שעדיף לכם לחזור למודל של שורה במשלוחים
פר תרומה - כאשר את הפירוט לסוגי המכשירים, אפשר לשים בשדות החדשים שהוגדר
עבור סם הערות A1, A2, A3, A4 - או אפילו באיזה מבנה JSON שיאכסן אותם
באחד השדות הללו.
