### ISSUE TITLE
מתנדב עצמאי ייראה רק משלוחים עם פחות מ 6 פריטים

### ISSUE THREAD

**Issue by morfi11** [noam-honig/food-basket-delivery#676]
משלוחים גדולים עם 5 פריטים ויותר ישתייכו רק על ידי הרכזים
המספר 5 יעודכן בהגדרות מערכת - מקסימום פריטים לשיוך עצמי
בנוסף - אין לאפשר שיוך עצמי של משלוחים עם גורם מפנה = בית עסק
ובנוסף - אין לאפשר למתנדב עצמאי לשייך לעצמו יותר משלושה תורמים בכל רגע נתון. 

כלומר אם כבר משוייך לו תורם אחד בסטטוס "מוכן למשלוח", הוא יוכל להוסיף רק 2. 

רק לאחר שרשימת הממתינים לאיסוף קטנה מ 3 - ניתן לשייך לעצמו משלוחים נוספים

**Comment by noam-honig** [comment]
אתה מתכוון שלא ישויכו על ידי מתנדב בשיוך עצמי.
