### ISSUE TITLE
בעייה בקליטת משפחות קיימות מאקסל 

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#705]
קליטת רשימה קיימת
הוספת סל חדש 
הוספת רשימת תפוצה חדשה
לא ממשיך לשלב הבא
![image](https://user-images.githubusercontent.com/20454933/122080494-fb873580-ce06-11eb-9491-32b532369d56.png)

![2021-06-15_18h16_01](https://user-images.githubusercontent.com/20454933/122079619-42286000-ce06-11eb-8b8f-f6758b12c56f.png)
![2021-06-15_18h15_53](https://user-images.githubusercontent.com/20454933/122079624-42c0f680-ce06-11eb-97de-1894c42ebf52.png)
![2021-06-15_18h21_25](https://user-images.githubusercontent.com/20454933/122080065-a3503380-ce06-11eb-9b49-18c9b5d29977.png)

**Comment by noam-honig** [comment]
אני מבין שהטסט שלך נכשל.
אני חושב שזה פחות קשור לרשימה החדשה - ויותר לקובץ עצמו / לשדות עצמם.
אתה רוצה לשלוח לי את הקובץ שאתה קולט איתו - ולסמן בדיוק אילו שדות בחרת לאיזה עמודות כשקיבלת את השגיאה?

**Comment by menachemai** [comment]
בישן זה נפתח טוב,
שולח לך את הקובץ בנפרד

On Thu, Jun 17, 2021 at 5:43 PM Noam Honig ***@***.***> wrote:

> אני מבין שהטסט שלך נכשל.
> אני חושב שזה פחות קשור לרשימה החדשה - ויותר לקובץ עצמו / לשדות עצמם.
> אתה רוצה לשלוח לי את הקובץ שאתה קולט איתו - ולסמן בדיוק אילו שדות בחרת
> לאיזה עמודות כשקיבלת את השגיאה?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/81d938b45525c1c243c0ff4e5aa3bad9a1829717?url=https%3A%2F%2Fgithub.com%2Fnoam-honig%2Ffood-basket-delivery%2Fissues%2F705%23issuecomment-863300910&userId=2198057&signature=6118b8e158ce91d4>,
> or unsubscribe
> <https://mailtrack.io/trace/link/9f58569efc1f2684942cc4c1703147b20bb0cd02?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE4B4FI72HRBPOSXEWYPDY3TTICYTANCNFSM46XQKEOQ&userId=2198057&signature=f7ef267ed237902b>
> .
>


-- 
*Menachem Ainemer** | COO*
*Cell +972.52.3307014 *
*Tel    +972.3.9197373 *
*Fax   +972.3.9197371 *
*www.fireflymigration.com
<https://mailtrack.io/trace/link/5838fc5de5b1ff89b25e092909a89c64796f971d?url=http%3A%2F%2Fwww.fireflymigration.com%2F&userId=2198057&signature=2ccf24d0be1190e9>*
[image: Inline image 1]
[image: Inline image 5]
<https://mailtrack.io/trace/link/15b6c0c71ffb368eadd0e2886d033a0800d2227c?url=http%3A%2F%2Fwww.youtube.com%2Ffireflymigration&userId=2198057&signature=f0f1b559ce94c1f5>[image:
Inline image 4]
<https://mailtrack.io/trace/link/4e2108a2410ac7c1a264b9bf31ef28a56ef0d5ca?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffirefly-migration%2F100-automated-migration-from-magic-unipaas-xpa-to-net-23400981%2Fproduct&userId=2198057&signature=2425aa2c0c5fabdd>

**Comment by noam-honig** [comment]
זה היה קשור לשדה טלפון - ושורות בלי ערך בכלל :)
