### ISSUE TITLE
חסר האיקון של הפח מחיקה

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#706]
הגדרות מערכת
סוגי סלים/ קבוצות שיוך משפחה
חסר האיקון של הפח משמאל
![2021-06-16_11h10_55](https://user-images.githubusercontent.com/20454933/122183231-b3622480-ce93-11eb-99ee-592ded34c6b3.png)

![2021-06-16_11h11_08](https://user-images.githubusercontent.com/20454933/122183085-90d00b80-ce93-11eb-8750-9913f25ae5f3.png)

**Comment by noam-honig** [comment]
זה בכוונה - אני רוצה שמחיקה יהיה פחות זמין - זה עדיין מופיע בתפריט שלש נקודות מימין
