### ISSUE TITLE
פתיחת חלוקה חדשה בגרסה הקיימת

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#711]
בגרסה הקיימת מופיע {"value":""}

בחדשה תקין
![2021-06-23_14h07_09](https://user-images.githubusercontent.com/20454933/123086719-70bcc100-d42c-11eb-901f-3212a7b73453.png)

**Comment by noam-honig** [comment]
בגרסא החדשה - תעשה פתיחת חלוקה חדשה - ונקה את שדה הקבוצות.
אחרי זה - זה יהיה תקין בשתיהן
