### ISSUE TITLE
כניסה למערכת עם אישור תנאי שימוש

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#719]
בחדש לא נפתחת האפשרות עם צ'ק בוקס לאשור לכן לא ניתן להכנס

![image](https://user-images.githubusercontent.com/20454933/125195872-5eca8300-e260-11eb-9d3a-985b8906d6be.png)

נוכחי תקין

![2021-07-11_15h52_25](https://user-images.githubusercontent.com/20454933/125195890-6db13580-e260-11eb-81d2-13624c65934a.png)

**Comment by menachemai** [comment]
כרגע נראה שזה לא פעיל ב2 הגרסאות
הכניסה רגילה
![image](https://user-images.githubusercontent.com/20454933/125592723-59713d55-2282-43bd-a3f9-774458ed1acd.png)

![2021-07-14_11h46_15](https://user-images.githubusercontent.com/20454933/125592738-7bcd1889-b49c-4a9c-871f-f6eefb16576d.png)

**Comment by noam-honig** [comment]
תנסה עם משתמש חדש.

אחרי שהסכמת פעם אחת לתנאים הוא לא שואל יותר
