### ISSUE TITLE
בתפריט נקודת חלוקה - מופיעה קטגורית ארועים

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#721]
נכנס כמנהל אזור
טלפון 0193232324
סיסמה
1234

בחדש
![image](https://user-images.githubusercontent.com/20454933/125301777-fb118a00-e333-11eb-98b7-b50a84775f4a.png)
 

בנוכחי לא מופיע

![image](https://user-images.githubusercontent.com/20454933/125301899-1b414900-e334-11eb-9e63-5c9861d7d53c.png)

**Comment by noam-honig** [comment]
זה בסדר - למעשה הבעיה היא בסביבת הבדיקה של הקיים - שהיא לא מעודכנת לגרסא הממש אחרונה
