### ISSUE TITLE
 כתובות לא תקינות - לא קשור לגרסה החדשה 

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#724]
קלטתי אקסל עם כתובת דומה "שדרות העצמאות" בערים שונות בארץ
ניתן לראות ברשימת חלוקה- קבוצה 9
 **כל הערים** שאין בהם את שדרות העצמאות הוא קבע שהכתובת שגוגל הבין היא בבת ים
לא יודע אם זה קשור אליך או לגוגל.

**Comment by noam-honig** [comment]
זה גוגל - אין לי שום שליטה על זה
