### ISSUE TITLE
לא נקלט טלפון 1 מהאקסל

### ISSUE THREAD

**Issue by menachemai** [noam-honig/food-basket-delivery#725]
קליטת אקסל עם רשימת טלפונים, כולל מספרים מוזרים.
בפועל לא קלט אף מספר
טלפון 2 גם לא נקלט
![2021-07-26_16h06_16](https://user-images.githubusercontent.com/20454933/126993545-80e02697-51f4-45b8-a6ed-eacdb3218900.png)

![image](https://user-images.githubusercontent.com/20454933/126994166-878a2ef9-920f-47fb-bc3a-01d7aeea8058.png)

**Comment by noam-honig** [comment]
שלח לי בבקשה במייל את האקסל שהשתמשת בו - וצילום מסך של מיפוי העמודות.
(אני חושד שהיתה עמודת טלפון שדרסה את טלפון 1)
