### ISSUE TITLE
אופציה של מתנדב שלא הגיע

### ISSUE THREAD

**Issue by yaelal** [noam-honig/food-basket-delivery#769]
קורה אצלנו שמתנדב לא מגיע וכל המשלוחים שלו לא מחולקים
היה נחמד אם כמו שאפשר לסמן שהכל נמסר יהיה אפשר לסמן שהכל לא נמסר 
ובכלל שיהיה אופציה לסמן שלא נמסר כי אין מתנדב/משנע
תודה

**Comment by yaelal** [comment]
אני לא רואה אופציה לסמן שלא נמסר כי אין משלח

**Comment by noam-honig** [comment]
סיכמנו שתבטלי שיוך. ואז במשלוחים פעילים אלו שלא שוייכו תסמני במקום שלא
נמסרו

**Comment by yaelal** [comment]
לא, התכונתי להוסיף אופציה בסיבות ללמה לא נמסר

**Comment by noam-honig** [comment]
את יכולה לערוך את הסיבות בהגדרות מערכת - הודעות למתנדב

**Comment by yaelal** [comment]
זה לא הודעה למתנדב
זה סיבה למה המשלוח לא נמסר

**Comment by noam-honig** [comment]
ברור - אבל שם את יכולה להגדיר הגדרות שכאלו
