### ISSUE TITLE
הזדמנות התנדבות לא מופיעה בלינק שנשלח

### ISSUE THREAD

**Issue by omri374** [noam-honig/food-basket-delivery#772]
אהלן,

אני לא מצליח לשלוח למתנדבים פוטנציאלים את ההזדמנות להתנדבות.

1. יצרתי הזדמנות התנדבות:
![image](https://user-images.githubusercontent.com/3776619/185970172-d68af3ed-e3f5-4a9a-a3af-aa94a02d2ebc.png)

2. לחצתי על "העתק קישור לרישום עצמי של מתנדבים"
3. שלחתי לינק.

מתקבל דף ריק (אני רואה את ההזדמנויות אבל מישהו שהוא לא יוזר לא רואה)

![image](https://user-images.githubusercontent.com/3776619/185970670-566c36b9-e021-47ca-b7fa-92f18bfa6a85.png)

האם אני עושה משהו לא נכון?

**Comment by noam-honig** [comment]
שים לב לתאריך ההתנדבות. מוצגים רק תאריכים עתידיים שהסטטוס פעיל

**Comment by omri374** [comment]
מדובר על אירוע עתידי בסטטוס "פתוח לרישום":

![image](https://user-images.githubusercontent.com/3776619/186079028-37f077c6-d91a-498c-9cd9-bdf977460a42.png)

**Comment by noam-honig** [comment]
הי Omri, שים לב שלא מופיע לו למטה Custom URL.

אם יש Custom URL - האירוע יופיע רק עבור מי שניגש עם הCustom URL.

שם לב גם שהCUSTOM URL נועד לתפקד כסיומת, לא כURL מלא.

לדוגמוא - מי ששם custom url - שנקרא demo - הכתובת שתגיע אליו היא
https://salmaz.herokuapp.com/test/events/demo

**Comment by noam-honig** [comment]
אם הנושא סגור, אשמח אם תסגור את הISSUE
