### ISSUE TITLE
הוספת קטגורית "חלוקת כרטיסי מזון" בהזדמנות להתנדבות

### ISSUE THREAD

**Issue by omri374** [noam-honig/food-basket-delivery#773]
אהלן,
האם ניתן להוסיף קטגוריה נוספת לסוג ההתנדבות (כרטיסי מזון)? או לחילופין לאפשר לנו להוסיף מידע במידה ובוחרים "אחר"?

![image](https://user-images.githubusercontent.com/3776619/185970867-d3bef947-25a9-44d2-948b-54de26754dd5.png)

אם בוחרים אחר זה נראה קצת מוזר:
![image](https://user-images.githubusercontent.com/3776619/185971043-4bb9a4a5-7a3a-46b1-9a20-99a3b2f3c7dc.png)

תודה כמובן על האפליקציה המופלאה !!

**Comment by noam-honig** [comment]
האם מספיק, שבמקרה של אחר - לא אציג את הפסיק אחר - ואת המידע תכתוב
בתאור אירוע?

**Comment by omri374** [comment]
כן

**Comment by noam-honig** [comment]
בוצע - תרענן בבקשה את הדפדפן
